In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier

import sklearn.metrics as metrics
from sklearn.model_selection import learning_curve

In [2]:
data = pd.read_csv("../Data Science/datasets/weatherAUS.csv.zip")

In [3]:
data.head(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [4]:
columnas_descartables = ['Sunshine', 'Evaporation','Cloud3pm','Cloud9am', 'Location','Date']
data = data.drop(columns=columnas_descartables)
data = data.dropna()

In [5]:
columnas_descartables = ['WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']
data = data.drop(columns=columnas_descartables)

In [6]:
data = data.drop(columns=['Temp3pm', 'Pressure9am'])

In [7]:
data['RainTomorrow'] = data['RainTomorrow'].map({'Yes': 1, 'No': 0})

In [8]:
data.head(5)

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure3pm,Temp9am,RainTomorrow
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.1,16.9,0
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1007.8,17.2,0
2,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1008.7,21.0,0
3,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1012.8,18.1,0
4,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1006.0,17.8,0

In [9]:
columns_entrenamiento = ['MaxTemp', 'Humidity3pm']
X = data[columns_entrenamiento]
y = data.RainTomorrow

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.30, random_state= 42, stratify= y)

In [11]:
X_train

        MaxTemp  Humidity3pm
6561       18.6         57.0
98223      26.0         41.0
70776      28.2         23.0
97526      23.4         59.0
112646     30.9         34.0
...         ...          ...
19882      23.9         53.0
83362      21.9         41.0
105266     13.1         67.0
101009     20.9         43.0
100089     12.1         91.0

[79047 rows x 2 columns]

In [12]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
accuracy_score(y_test,y_pred_dt)

0.8046519865399374

In [18]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.83      0.94      0.88     26372
           1       0.60      0.34      0.44      7506

    accuracy                           0.80     33878
   macro avg       0.72      0.64      0.66     33878
weighted avg       0.78      0.80      0.78     33878

In [17]:
confusion_matrix(y_test,y_pred_dt)

array([[24673,  1699],
       [ 4919,  2587]])

In [19]:
from xgboost import XGBClassifier

In [20]:
xgb_model = XGBClassifier(random_state=42,use_label_encoder = False, eval_metrics ='logloss')
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)

In [21]:
accuracy_score(y_test,y_pred_xgb)

0.8303323690890844

In [22]:
print(classification_report(y_test,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.84      0.96      0.90     26372
           1       0.74      0.36      0.49      7506

    accuracy                           0.83     33878
   macro avg       0.79      0.66      0.69     33878
weighted avg       0.82      0.83      0.81     33878

In [24]:
confusion_matrix(y_test,y_pred_xgb)

array([[25404,   968],
       [ 4780,  2726]])